# Generated by Django 3.1.3 on 2020-11-29 10:44

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20201129_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(upload_to='post_images'),
        ),
    ]
